language: scala
scala: 3.0.0-M1
jdk: openjdk11
script:
- "./build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: gh-pages
  on:
    branch: master
